main: me.playbosswar.com.CommandTimerPlugin
name: "CommandTimer"
version: "8.5.3"
description: "Schedule commands like you want"
author: PlayBossWar
api-version: 1.13
softdepend: [ PlaceholderAPI ]

commands:
  commandtimer:
    usage: /<command>
    aliases: [ cmt ]
    description: List all commands