main: me.playbosswar.com.CommandTimerPlugin
name: "CommandTimer"
version: "6.0.0-BETA-4"
description: "Schedule commands like you want"
author: PlayBossWar
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  commandtimer:
    usage: /<command>
    aliases: [cmt]
    description: List all commands