name: Test that everything can build properly and is tested
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  Build-Java-8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: gradle :shadowJar -b java8-build.gradle
  Build-Java-17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: gradle :shadowJar
  test-documentation:
    name: Test Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: docs/yarn.lock
      - name: Install dependencies
        working-directory: ./docs
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: ./docs
        run: yarn build
